spring.cloud.config.enabled=false
spring.config.import=optional:
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
management.endpoints.web.exposure.include=health,prometheus
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans
eureka.instance.prefer-ip-address=true
