apiVersion: v1
kind: Service
metadata:
  name: biblioteca
  namespace: biblioteca
spec:
  selector:
    app: biblioteca
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioteca
  namespace: biblioteca
spec:
  replicas: 3
  selector:
    matchLabels:
      app: biblioteca
  template:
    metadata:
      labels:
        app: biblioteca
    spec:
      containers:
        - name: biblioteca
          image: projeto_de_bloco-biblioteca:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DB_PASSWORD
              value: "123456"