apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: biblioteca
spec:
  selector:
    app: loan-service
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: biblioteca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
        - name: loan-service
          image: projeto_de_bloco-loan-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DB_PASSWORD
              value: "123456"
